services:
  - type: web
    name: gpuoptimizer
    env: python
    plan: free
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install -r requirements-render.txt
    startCommand: python gpu_optimizer_system.py
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
