apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpuoptimizer-app
  namespace: gpuoptimizer
  labels:
    app: gpuoptimizer-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gpuoptimizer-app
  template:
    metadata:
      labels:
        app: gpuoptimizer-app
    spec:
      containers:
      - name: gpuoptimizer
        image: gpuoptimizer:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: gpuoptimizer-config
              key: FLASK_ENV
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: gpuoptimizer-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: gpuoptimizer-config
              key: REDIS_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: gpuoptimizer-secrets
              key: SECRET_KEY
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: gpuoptimizer-secrets
              key: ENCRYPTION_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gpuoptimizer-secrets
              key: DB_PASSWORD
        - name: FLUTTERWAVE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: gpuoptimizer-secrets
              key: FLUTTERWAVE_SECRET_KEY
        - name: FLUTTERWAVE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: gpuoptimizer-secrets
              key: FLUTTERWAVE_PUBLIC_KEY
        - name: NOWPAYMENTS_API_KEY
          valueFrom:
            secretKeyRef:
              name: gpuoptimizer-secrets
              key: NOWPAYMENTS_API_KEY
        - name: NOWPAYMENTS_IPN_SECRET
          valueFrom:
            secretKeyRef:
              name: gpuoptimizer-secrets
              key: NOWPAYMENTS_IPN_SECRET
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: app-data
          mountPath: /app/data
        - name: app-logs
          mountPath: /app/logs
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: gpuoptimizer-data-pvc
      - name: app-logs
        persistentVolumeClaim:
          claimName: gpuoptimizer-logs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: gpuoptimizer-service
  namespace: gpuoptimizer
  labels:
    app: gpuoptimizer-app
spec:
  selector:
    app: gpuoptimizer-app
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpuoptimizer-data-pvc
  namespace: gpuoptimizer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpuoptimizer-logs-pvc
  namespace: gpuoptimizer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd
